version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated pr"
      - "non-owner pull request"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "dependencies"
      - "automated pr"
      - "javascript"
      - "non-owner pull request"

 # - package-ecosystem: "pip"
 #   directory: "/"
 #   schedule:
 #     interval: "daily"
 #     time: "00:00"
 #   ignore:
 #     - dependency-name: "*"
 #       update-types: ["version-update:semver-major"]
 #   labels:
 #     - "dependencies"
 #     - "automated pr"
 #     - "non-owner pull request"
