name: Greeting

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    if: ${{ (github.event.pull_request.user.login != 'jge162') && (github.actor != 'dependabot[bot]') }}
    # Will not run for owner or dependabot
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
            Welcome to the REPO, This is your first time Opening an Issue!
        pr-message: |
            Welcome to the REPO, This is your first time Opening an Pull Request!
